- app/connectors/VatRegistrationConnector.scala
- app/controllers/TaxableTurnoverController.scala
- app/controllers/ThresholdSummaryController.scala
- app/controllers/VatRegistrationController.scala
- app/models/S4LModels.scala
- it/controllers/EligibilityControllerISpec.scala
- it/controllers/ThresholdControllerISpec.scala
- it/controllers/ThresholdSummaryControllerISpec.scala
- it/helpers/RequestsFinder.scala
- it/support/AppAndStubs.scala
- it/support/StartAndStopWireMock.scala
- it/support/StubUtils.scala
- test/connectors/VatRegistrationConnectorSpec.scala
> fix and add more IT tests

- app/views/pages/applying_for_any_of.scala.html
- app/views/pages/applying_for_vat_exemption.scala.html
- app/views/pages/company_will_do_any_of.scala.html
- app/views/pages/do_any_apply_to_you.scala.html
- app/views/pages/doing_business_abroad.scala.html
- app/views/pages/have_nino.scala.html
- app/views/pages/taxable_turnover.scala.html
- app/views/pages/voluntary_registration.scala.html
- app/views/pages/voluntary_registration_reason.scala.html
... and removing superfluous fieldset wrappers and redundant spans with duplicated ID's
> Adding descriptive legends to fieldsets

- app/connectors/CompanyRegistrationConnector.scala
- app/connectors/IncorporationInformationConnector.scala
- conf/application.conf
**Bug fix**
Config value for incorporation-frontend stubs was corrected
> [SCRS-11579]fixed ifs bug

- project/FrontendBuild.scala
- project/build.properties
- project/plugins.sbt
SCRS-12086 dependencies uplift and protocol change
> SCRS-12086 dependencies uplift and protocol change

- app/controllers/IndexController.scala
- app/identifiers/Identifier.scala
- app/identifiers/ThresholdNextThirtyDaysId.scala
- app/utils/Navigator.scala
- app/utils/PageIdBinding.scala
- conf/app.routes
- it/www/ApplicantUKNinoISpec.scala
- it/www/IndexControllerSpec.scala
- project/FrontendBuild.scala
- project/MicroService.scala
- project/plugins.sbt
- test/controllers/IndexControllerSpec.scala
- test/utils/NavigatorSpec.scala
Needs squashing before merging
Added route question?pageId
uplifted dependencies
changed summary headings
* [] I've added my code using logical, atomic commits, squashing as appropriate - including the Jira issue number in the commit message
> Scrs 11819

- app/services/ThresholdService.scala
SCRS-11875b fix to dynamic content on previous 30 days page
**Bug fix 
* [X ] I've included appropriate tests with any code I've added
* [X ] I've executed the acceptance test pack locally to ensure there are no regressions
* [X ] I've added my code using logical, atomic commits, squashing as appropriate - including the Jira issue number in the commit message
* [X ] I've run a dependency check to ensure all dependencies are up to date
> SCRS-11875b fix to dynamic content on previous 30 days page

- conf/messages.en
- project/FrontendBuild.scala
SCRS-10853 Update of page titles and URIs
New feature
* [ X] I've included appropriate tests with any code I've added
* [ X] I've executed the acceptance test pack locally to ensure there are no regressions
* [ X] I've added my code using logical, atomic commits, squashing as appropriate - including the Jira issue number in the commit message
* [ X] I've run a dependency check to ensure all dependencies are up to date
> SCRS-10853 Update of page titles and URIs and dependency uplift

- project/FrontendBuild.scala
- project/MicroService.scala
- project/plugins.sbt
SCRS-12013 new build env changes/uplifts
> SCRS-12013 new build env changes/uplifts

- conf/application.conf
- project/FrontendBuild.scala
- project/plugins.sbt
Changed assets_frontend to 3.7.0 from 3.2.2 and updated all dependencies except bootstrap-play-25 as it was having issues.
> Scrs 12001 vrefe

- app/config/FrontendAppWiring.scala
- app/filters/WhitelistFilter.scala
- project/FrontendBuild.scala
> SCRS-12377 dep uplifts

- conf/application.conf
> SAR-4361: SSLEngine exception fix

- conf/application.conf
- test/controllers/RacehorsesControllerSpec.scala
> SAR-6058 Update VAT-REG-FE pass over first page

- app/views/vatRegistrationException.scala.html
- conf/messages.en
> SAR-6104: Updated content for VAT Registration Exception page

- app/controllers/SessionExpiredController.scala
- app/views/session_expired.scala.html
- test/controllers/SessionExpiredControllerSpec.scala
> Add session expired page back in

- app/views/agriculturalDropout.scala.html
- app/views/agriculturalFlatRateScheme.scala.html
- conf/messages.en
* [y ] I've included appropriate tests with any code I've added
* [ y] I've executed the acceptance test pack locally to ensure there are no regressions
* [ y] I've added my code using logical, atomic commits, squashing as appropriate - including the Jira issue number in the commit message
* [ y] I've run a dependency check to ensure all dependencies are up to date
> SAR-6106 Content update to AFRS page

- app/views/racehorses.scala.html
- conf/messages.en
- test/views/RacehorsesViewSpec.scala
* [y ] I've included appropriate tests with any code I've added
* [ y] I've executed the acceptance test pack locally to ensure there are no regressions
* [ y] I've added my code using logical, atomic commits, squashing as appropriate - including the Jira issue number in the commit message
* [y ] I've run a dependency check to ensure all dependencies are up to date
> SAR-6110 Content update to racehorses page

- app/views/choseNotToRegister.scala.html
- app/views/vatRegistrationException.scala.html
- app/views/voluntaryRegistration.scala.html
- conf/messages.en
- test/views/BaseSelectors.scala
- test/views/ChoseNotToRegisterViewSpec.scala
- test/views/VATRegistrationExceptionViewSpec.scala
- test/views/VoluntaryRegistrationViewSpec.scala
> SAR-6108: Updated content for Register Voluntarily page and tests

- test/views/EligibilityDropoutViewSpec.scala
- test/views/VATRegistrationExceptionViewSpec.scala
> SAR-6070: Updated viewspec tests for VAT Reg Exception and Eligibility Dropout

- test/views/BaseSelectors.scala
> Removed extra divs from Base Selectors

- test/views/AgriculturalFlatRateSchemeViewSpec.scala
- test/views/VATRegistrationExceptionViewSpec.scala
- test/views/VoluntaryRegistrationViewSpec.scala
> SAR-6130: Updated viewspec for AFRS

- test/views/AgriculturalFlatRateSchemeViewSpec.scala
- test/views/VATRegistrationExceptionViewSpec.scala
- test/views/VoluntaryRegistrationViewSpec.scala
> SAR-6130 brought back this commit

- app/views/internationalActivities.scala.html
- app/views/internationalActivityDropout.scala.html
- conf/messages.en
- test/views/EligibilityDropoutViewSpec.scala
- test/views/InternationalActivitiesViewSpec.scala
> SAR-6116: Updated content for International Activities page

- conf/application.conf
- test/controllers/RacehorsesControllerSpec.scala
> SAR-6121 Changed pass over to new honesty declaration page

- app/controllers/ThresholdPreviousThirtyDaysController.scala
- app/controllers/TurnoverEstimateController.scala
- app/forms/TurnoverEstimateFormProvider.scala
- app/models/TurnoverEstimate.scala
- app/services/VatRegistrationService.scala
- app/views/newcomponents/h1.scala.html
- app/views/turnoverEstimate.scala.html
- conf/messages.en
- test/controllers/TurnoverEstimateControllerSpec.scala
- test/forms/TurnoverEstimateFormProviderSpec.scala
- test/services/VatRegistrationServiceSpec.scala
- test/utils/PageIdBindingSpec.scala
- test/views/AgriculturalFlatRateSchemeViewSpec.scala
- test/views/TurnoverEstimateViewSpec.scala
* [ y] I've included appropriate tests with any code I've added
* [y ] I've executed the acceptance test pack locally to ensure there are no regressions
* [ y] I've added my code using logical, atomic commits, squashing as appropriate - including the Jira issue number in the commit message
> SAR-6118 Content update to turnover estimate page

- app/views/thresholdNextThirtyDays.scala.html
- conf/messages.en
* [] I've executed the acceptance test pack locally to ensure there are no regressions
> SAR-6162 Updated Content for thresholdNextThirtyDays

- app/views/vatExemption.scala.html
- conf/messages.en
- test/views/VATExemptionViewSpec.scala
> SAR-6171: Updated content for VAT Exemption page

- conf/messages.en
> SAR-6202: Updated validation message for VAT Exemption page

- conf/messages.en
> SAR-6209: Updated validation message

- app/controllers/RegisteringBusinessController.scala
- app/forms/RegisteringBusinessFormProvider.scala
- app/identifiers/RegisteringBusinessId.scala
- app/utils/Navigator.scala
- app/utils/PageIdBinding.scala
- app/utils/UserAnswers.scala
- app/views/newcomponents/yesNoRadio.scala.html
- app/views/registeringBusiness.scala.html
- conf/app.routes
- conf/messages.en
- test/controllers/RegisteringBusinessControllerSpec.scala
- test/forms/RegisteringBusinessFormProviderSpec.scala
- test/services/VatRegistrationServiceSpec.scala
- test/utils/PageIdBindingSpec.scala
- test/views/RegisteringBusinessViewSpec.scala
> SAR-6166 added RegisteringBusiness page

- it/www/ZeroRateSalesISpec.scala
> SAR-6166 Fixed IT Tests

- app/controllers/NinoController.scala
- app/forms/NinoFormProvider.scala
- app/identifiers/NinoId.scala
- app/utils/Navigator.scala
- app/utils/PageIdBinding.scala
- app/utils/UserAnswers.scala
- app/views/nino.scala.html
- conf/app.routes
- conf/messages.en
- it/www/NinoControllerISpec.scala
- test/controllers/NinoControllerSpec.scala
- test/forms/NinoFormProviderSpec.scala
- test/services/VatRegistrationServiceSpec.scala
- test/utils/PageIdBindingSpec.scala
- test/views/NinoViewSpec.scala
> SAR-6173: Added controller, view, form and tests for Nino page

- app/controllers/IntroductionController.scala
- app/identifiers/IntroductionId.scala
- app/utils/Navigator.scala
- app/views/introduction.scala.html
- conf/app.routes
- conf/logback-test.xml
- conf/messages.en
- it/www/IndexControllerSpec.scala
- it/www/IntroductionControllerISpec.scala
- test/controllers/IndexControllerSpec.scala
- test/controllers/IntroductionControllerSpec.scala
- test/utils/NavigatorSpec.scala
- test/views/IntroductionViewSpec.scala
> SAR-6247: Add Introduction page

- app/controllers/EligibleController.scala
- app/controllers/RacehorsesController.scala
- app/identifiers/EligibleId.scala
- app/utils/Navigator.scala
- app/views/eligible.scala.html
- app/views/racehorses.scala.html
- conf/app.routes
- conf/messages.en
- it/helpers/AuthHelpers.scala
- it/helpers/VatRegistrationStub.scala
- it/www/EligibleControllerISpec.scala
- test/controllers/EligibleControllerSpec.scala
- test/controllers/RacehorsesControllerSpec.scala
- test/views/EligibleViewSpec.scala
> SAR-6258: Add eligible page

- app/controllers/BusinessEntityController.scala
- app/controllers/IntroductionController.scala
- app/forms/BusinessEntityFormProvider.scala
- app/identifiers/BusinessEntityId.scala
- app/models/BusinessEntity.scala
- app/services/VatRegistrationService.scala
- app/utils/Navigator.scala
- app/utils/PageIdBinding.scala
- app/utils/UserAnswers.scala
- app/views/businessEntity.scala.html
- conf/app.routes
- conf/messages.en
- it/www/EligibleControllerISpec.scala
- it/www/IntroductionControllerISpec.scala
- test/controllers/BusinessEntityControllerSpec.scala
- test/controllers/IntroductionControllerSpec.scala
- test/forms/BusinessEntityFormProviderSpec.scala
- test/services/VatRegistrationServiceSpec.scala
- test/utils/PageIdBindingSpec.scala
- test/views/BusinessEntityViewSpec.scala
> SAR-6183 Added business entity  page

- app/controllers/VATExemptionController.scala
- app/utils/Navigator.scala
- it/www/AnnualAccountingSchemeISpec.scala
- it/www/VATExemptionISpec.scala
> SAR-6293: Update routes for VAT Exemption and Agricultural FRS

- app/utils/Navigator.scala
- app/views/businessEntity.scala.html
> SAR-6392 Fixed MTD Voluntary page location in journey

- app/config/FrontendAppConfig.scala
- app/controllers/MandatoryInformationController.scala
- app/identifiers/MandatoryInformationId.scala
- app/utils/Navigator.scala
- app/utils/UserAnswers.scala
- app/views/mandatoryInformation.scala.html
- conf/app.routes
- conf/application.conf
- conf/messages.en
- test/controllers/InformationControllerSpec.scala
- test/views/MandatoryInformationViewSpec.scala
> SAR-6449 Mandatory MTD VAT signup page

- app/config/FrontendAppConfig.scala
- app/connectors/TrafficManagementConnector.scala
- app/featureswitch/api/controllers/FeatureSwitchApiController.scala
- app/featureswitch/api/services/FeatureSwitchService.scala
- app/featureswitch/core/config/FeatureSwitchRegistry.scala
- app/featureswitch/core/config/FeatureSwitching.scala
- app/featureswitch/core/config/FeatureSwitchingModule.scala
- app/featureswitch/core/models/FeatureSwitch.scala
- app/featureswitch/core/models/FeatureSwitchSetting.scala
- app/services/TrafficManagementService.scala
- conf/application.conf
- conf/test.routes
- conf/testOnlyDoNotUseInAppConf.routes
- it/connectors/TrafficManagementConnectorISpec.scala
- it/helpers/FakeTimeMachine.scala
- it/helpers/TrafficManagementStub.scala
- it/www/ThresholdInTwelveMonthsControllerISpec.scala
- it/www/ThresholdNextThirtyDaysISpec.scala
- it/www/ThresholdPreviousThirtyDaysISpec.scala
- test/mocks/TrafficManagementConnectorMock.scala
- test/services/TrafficManagementServiceSpec.scala
> SAR-6509: Connection to traffic management API

- app/connectors/DataCacheConnector.scala
- app/controllers/IndexController.scala
- app/repositories/SessionRepository.scala
- test/connectors/FakeDataCacheConnector.scala
- test/controllers/IndexControllerSpec.scala
> fixed EL ignoring new regId after relogging

- app/controllers/ZeroRatedSalesController.scala
- app/utils/Navigator.scala
- app/utils/PageIdBinding.scala
- app/utils/ThresholdHelper.scala
- it/www/AnnualAccountingSchemeISpec.scala
- it/www/NinoControllerISpec.scala
- it/www/ThresholdNextThirtyDaysISpec.scala
- it/www/ThresholdPreviousThirtyDaysISpec.scala
- it/www/VATExemptionISpec.scala
- it/www/VATRegistrationExceptionISpec.scala
- it/www/ZeroRateSalesISpec.scala
- test/services/VatRegistrationServiceSpec.scala
SAR-6483 - Update order of screens
> SAR-6483 - Update order of screens

- app/config/FrontendAppConfig.scala
- app/views/google_tag_manager.scala.html
- app/views/govuk_wrapper.scala.html
- app/views/layouts/layout.scala.html
- conf/application.conf
> SAR-6515 Added GTM

- app/config/FrontendAppConfig.scala
- app/services/TrafficManagementService.scala
- app/utils/FakeTimeMachine.scala
- app/utils/IdGenerator.scala
- it/helpers/FakeTimeMachine.scala
- test/base/VATEligiblityMocks.scala
- test/services/TrafficManagementServiceSpec.scala
- test/utils/FakeIdGenerator.scala
> SAR-6557 Added audit when successfully passing traffic management

- app/config/FrontendAppConfig.scala
- app/controllers/EligibilityDropoutController.scala
- app/controllers/VATExceptionKickoutController.scala
- app/identifiers/VATExceptionKickoutId.scala
- app/utils/Navigator.scala
- app/utils/UserAnswers.scala
- app/views/vatDivisionDropout.scala.html
- app/views/vatExceptionDropout.scala.html
- app/views/vatExceptionKickout.scala.html
- conf/app.routes
- conf/application.conf
- conf/messages
- test/controllers/VATExceptionKickoutControllerSpec.scala
- test/views/VATExceptionKickoutViewSpec.scala
> SAR-6486 Adding logic for non UK companies

- app/config/FrontendAppConfig.scala
- app/controllers/FeedbackController.scala
- app/views/layouts/layout.scala.html
- app/views/newcomponents/phaseBanner.scala.html
- test/controllers/FeedbackControllerSpec.scala
> SAR-6584 - Update the phase banner and add feedback link

- app/utils/Navigator.scala
- conf/messages
- it/www/AnnualAccountingSchemeISpec.scala
> SAR-6563 UK Company flow kickout pages updateed

- app/utils/Navigator.scala
- it/www/NinoControllerISpec.scala
> SAR-6604 Exception kickout added for further 2 pages

- app/config/FrontendAppConfig.scala
- app/controllers/SignOutController.scala
- app/views/layouts/layout.scala.html
- app/views/newcomponents/siteHeader.scala.html
- conf/app.routes
- conf/application.conf
- it/repositories/SessionRepositoryISpec.scala
- it/www/IndexControllerISpec.scala
- project/MicroService.scala
- project/scaffold.sbt
- test/controllers/SignOutControllerSpec.scala
> SAR-6596 added signout link, made ITs faster

- conf/application.conf
> SAR-6613 - Update to otrs URL

- app/utils/Navigator.scala
- app/utils/PageIdBinding.scala
- test/utils/NavigatorSpec.scala
> SAR-6608 Ignore exemption if user selects an exception

- app/config/FrontendAppConfig.scala
- app/connectors/TrafficManagementConnector.scala
- app/controllers/EligibilityDropoutController.scala
- app/controllers/EligibleController.scala
- app/controllers/NinoController.scala
- app/controllers/ThresholdInTwelveMonthsController.scala
- app/controllers/VATExceptionKickoutController.scala
- app/models/RegistrationChannel.scala
- app/models/RegistrationInformation.scala
- app/models/RegistrationStatus.scala
- app/services/TrafficManagementService.scala
- conf/app.routes
- it/connectors/TrafficManagementConnectorISpec.scala
- it/helpers/AuthHelpers.scala
- it/helpers/TrafficManagementStub.scala
- it/www/EligibleControllerISpec.scala
- it/www/NinoControllerISpec.scala
- it/www/ThresholdInTwelveMonthsControllerISpec.scala
- test/controllers/EligibilityDropoutControllerSpec.scala
- test/controllers/EligibleControllerSpec.scala
- test/controllers/NinoControllerSpec.scala
- test/controllers/ThresholdInTwelveMonthsControllerSpec.scala
- test/controllers/VATExceptionKickoutControllerSpec.scala
- test/controllers/actions/FakeDataRetrievalAction.scala
- test/mocks/TrafficManagementServiceMock.scala
- test/services/TrafficManagementServiceSpec.scala
> SAR-6566: Integrate Traffic Management

- app/controllers/NinoController.scala
> SAR-6637: Traffic management logic fix

- app/views/newcomponents/errorSummary.scala.html
- app/views/thresholdInTwelveMonths.scala.html
- app/views/thresholdNextThirtyDays.scala.html
- app/views/thresholdPreviousThirtyDays.scala.html
- project/FrontendBuild.scala
**Bug fix**
**Note:** The DAC report only points out 2 views/pages with this issue. There was a 3rd view that had the same issue with the programmatic focus but was missing in the DAC report. All 3 are fixed in this PR.
> SAR-6686 - Fixed error summary link programmatic focus issue

- conf/messages
- test/views/InternationalActivitiesViewSpec.scala
* [yep] I've included appropriate tests with any code I've added
* [yip] I've executed the acceptance test pack locally to ensure there are no regressions
* [yup] I've added my code using logical, atomic commits, squashing as appropriate - including the Jira issue number in the commit message
> SAR-6652 Content update for International Activities Page

- app/config/FrontendAppConfig.scala
- app/views/layouts/layout.scala.html
- conf/application.conf
- project/FrontendBuild.scala
> SAR-6692 Add configurable js timeout script

- app/forms/mappings/Constraints.scala
- app/views/newcomponents/inputDate.scala.html
- app/views/thresholdInTwelveMonths.scala.html
- app/views/thresholdNextThirtyDays.scala.html
- app/views/thresholdPreviousThirtyDays.scala.html
- conf/messages
> SAR-6688 Remove pattern attribute from input + Check form validation

- app/config/FrontendAppConfig.scala
- app/controllers/EligibilityDropoutController.scala
- app/utils/Navigator.scala
- app/views/internationalActivities.scala.html
- app/views/internationalActivityDropout.scala.html
- conf/app.routes
- conf/application.conf
- conf/messages
- test/controllers/EligibilityDropoutControllerSpec.scala
- test/views/InternationalActivitiesViewSpec.scala
> SAR-6754 SAR-6757 Updated International Activities and Dropout to reflect EU Exit

- app/views/layouts/layout.scala.html
* [] I've run a dependency check to ensure all dependencies are up to date
> SAR-6829 Updated HMRC Footer to fix missing footer links

- app/views/govuk_wrapper.scala.html
- app/views/layouts/layout.scala.html
- build.sbt
- conf/application.conf
- project/AppDependencies.scala
> SAR-6944 Adding Tracking Consent

- app/controllers/actions/CacheIdentifierAction.scala
- test/controllers/actions/CacheIdentifierActionSpec.scala
> SAR-7032 updated the identifier action to redirect to VRFE when scheme is not found

- app/controllers/FixedEstablishmentController.scala
- app/controllers/IntroductionController.scala
- app/forms/FixedEstablishmentFormProvider.scala
- app/views/fixedEstablishment.scala.html
- conf/app.routes
- conf/messages
- it/www/IntroductionControllerISpec.scala
- test/controllers/FixedEstablishmentControllerSpec.scala
- test/controllers/IntroductionControllerSpec.scala
- test/views/FixedEstablishmentViewSpec.scala
> SAR-7238 Added fixed establishment page and controller

- app/controllers/FixedEstablishmentController.scala
- app/identifiers/FixedEstablishmentId.scala
- app/utils/Navigator.scala
- app/utils/PageIdBinding.scala
- app/utils/UserAnswers.scala
- it/www/EligibleControllerISpec.scala
- test/controllers/FixedEstablishmentControllerSpec.scala
- test/services/VatRegistrationServiceSpec.scala
- test/utils/PageIdBindingSpec.scala
> SAR-7239 Update controller to store the FixedEstablishment answer

- app/config/FrontendAppConfig.scala
- conf/messages
> SAR-7379b: Remove messages

- app/views/internationalActivities.scala.html
- conf/messages
- test/views/InternationalActivitiesViewSpec.scala
> SAR-7456 Added Brexit checker link to international activities

- app/views/error_template.scala.html
> Fixed error message template

- app/controllers/NinoController.scala
- app/controllers/actions/DataRetrievalAction.scala
- app/services/CurrentProfileService.scala
- app/services/S4LService.scala
- test/base/CommonSpecBase.scala
- test/base/VATEligibilityMocks.scala
- test/controllers/NinoControllerSpec.scala
- test/controllers/actions/DataRetrievalActionSpec.scala
- test/mocks/S4LServiceMock.scala
- test/services/CurrentProfileServiceSpec.scala
- test/services/VatRegistrationServiceSpec.scala
> SAR-7461: DataRetrievalAction and CurrentProfileService using S4L

- app/controllers/BusinessEntityController.scala
- app/forms/BusinessEntityFormProvider.scala
- app/models/BusinessEntity.scala
- app/services/VatRegistrationService.scala
- app/views/businessEntity.scala.html
- test/controllers/BusinessEntityControllerSpec.scala
- test/forms/BusinessEntityFormProviderSpec.scala
- test/services/VatRegistrationServiceSpec.scala
- test/utils/PageIdBindingSpec.scala
> SAR-7631 Updated the business entity model for future page changes

- app/controllers/BusinessEntityOtherController.scala
- app/controllers/BusinessEntityPartnershipController.scala
- app/forms/BusinessEntityFormProvider.scala
- app/forms/BusinessEntityOtherFormProvider.scala
- app/forms/BusinessEntityPartnershipFormProvider.scala
- app/identifiers/BusinessEntityOtherId.scala
- app/identifiers/BusinessEntityPartnershipId.scala
- app/models/BusinessEntity.scala
- app/utils/Navigator.scala
- app/views/businessEntity.scala.html
- app/views/businessEntityOther.scala.html
- app/views/businessEntityPartnership.scala.html
- conf/app.routes
- conf/messages
- test/controllers/BusinessEntityOtherControllerSpec.scala
- test/controllers/BusinessEntityPartnershipControllerSpec.scala
- test/forms/BusinessEntityOtherFormProviderSpec.scala
- test/forms/BusinessEntityPartnershipFormProviderSpec.scala
- test/views/BaseSelectors.scala
- test/views/BusinessEntityOtherViewSpec.scala
- test/views/BusinessEntityPartnershipViewSpec.scala
- test/views/BusinessEntityViewSpec.scala
> SAR-7632 Updated business entity selection

- app/featureswitch/core/config/FeatureSwitchingModule.scala
- app/utils/Navigator.scala
- test/views/BusinessEntityViewSpec.scala
> SAR-7670 Updated Business Entity to allow sole traders

- app/connectors/TrafficManagementConnector.scala
- app/featureswitch/core/config/FeatureSwitchingModule.scala
- app/models/BusinessEntity.scala
- app/views/businessEntity.scala.html
- app/views/businessEntityOther.scala.html
- app/views/businessEntityPartnership.scala.html
- test/services/VatRegistrationServiceSpec.scala
- test/views/BusinessEntityViewSpec.scala
> SAR-7857 Updated business entity keys to be compatible with BE

- app/featureswitch/core/config/FeatureSwitchingModule.scala
- app/utils/Navigator.scala
- it/www/InternationalActivitiesControllerISpec.scala
> SAR-8010 Added UnincorporatedAssociation FS to enable the flow

- app/controllers/BusinessEntityOverseasController.scala
- app/identifiers/BusinessEntityOverseasId.scala
- app/views/BusinessEntityOverseas.scala.html
- conf/app.routes
- conf/messages
- it/controllers/AnnualAccountingSchemeISpec.scala
- it/controllers/BusinessEntityOverseasControllerISpec.scala
- it/controllers/EligibleControllerISpec.scala
- it/controllers/IndexControllerISpec.scala
- it/controllers/InternationalActivitiesControllerISpec.scala
- it/controllers/IntroductionControllerISpec.scala
- it/controllers/NinoControllerISpec.scala
- it/controllers/RacehorsesISpec.scala
- it/controllers/ThresholdInTwelveMonthsControllerISpec.scala
- it/controllers/ThresholdNextThirtyDaysISpec.scala
- it/controllers/ThresholdPreviousThirtyDaysISpec.scala
- it/controllers/VATExemptionISpec.scala
- it/controllers/VATRegistrationExceptionISpec.scala
- it/controllers/ZeroRateSalesISpec.scala
- test/controllers/BusinessEntityOverseasControllerSpec.scala
- test/views/BusinessEntityOverseasViewSpec.scala
> SAR-8086 Added BusinessEntityOverseas page and dummy controller

- app/controllers/TaxableSuppliesInUkController.scala
- app/controllers/ThresholdInTwelveMonthsController.scala
- app/forms/TaxableSuppliesInUkFormProvider.scala
- app/identifiers/TaxableSuppliesInUkId.scala
- app/services/TrafficManagementService.scala
- app/utils/Navigator.scala
- app/utils/UserAnswers.scala
- app/views/TaxableSuppliesInUk.scala.html
- conf/app.routes
- conf/messages
- it/controllers/TaxableSuppliesInUkControllerISpec.scala
- test/views/TaxableSuppliesInUkViewSpec.scala
> SAR-8174 Added Taxable Supplies in UK Page

- app/controllers/DoNotNeedToRegisterController.scala
- app/identifiers/DoNotNeedToRegisterId.scala
- app/utils/Navigator.scala
- app/views/doNotNeedToRegister.scala.html
- conf/app.routes
- conf/messages
- it/controllers/TaxableSuppliesInUkControllerISpec.scala
- test/controllers/DoNotNeedToRegisterControllerSpec.scala
- test/views/DoNotNeedToRegisterViewSpec.scala
> SAR-8178: Added Do Not Need To Register controller, view and tests

- app/controllers/ThresholdTaxableSuppliesController.scala
- app/forms/ThresholdTaxableSuppliesFormProvider.scala
- app/forms/mappings/Constraints.scala
- app/identifiers/ThresholdTaxableSuppliesId.scala
- app/models/DateFormElement.scala
- app/utils/Navigator.scala
- app/utils/UserAnswers.scala
- app/views/ThresholdTaxableSupplies.scala.html
- conf/app.routes
- conf/messages
- it/controllers/TaxableSuppliesInUkControllerISpec.scala
- it/controllers/ThresholdTaxableSuppliesISpec.scala
- test/forms/ThresholdTaxableSuppliesFormProviderSpec.scala
- test/views/ThresholdTaxableSuppliesViewSpec.scala
> SAR-8175 Added Threshold Taxable Supplies Page

- app/config/FrontendAppConfig.scala
- app/controllers/GoneOverThresholdController.scala
- app/forms/GoneOverThresholdFormProvider.scala
- app/identifiers/GoneOverThresholdId.scala
- app/utils/Navigator.scala
- app/utils/UserAnswers.scala
- app/views/GoneOverThreshold.scala.html
- conf/app.routes
- conf/messages
- it/controllers/GoneOverThresholdControllerISpec.scala
- it/controllers/ThresholdTaxableSuppliesISpec.scala
- test/views/GoneOverThresholdViewSpec.scala
> SAR-8176: Gone over business threshold page

- app/forms/ThresholdTaxableSuppliesFormProvider.scala
- app/models/DateFormElement.scala
- app/services/VatRegistrationService.scala
- app/utils/PageIdBinding.scala
- test/forms/ThresholdTaxableSuppliesFormProviderSpec.scala
- test/utils/PageIdBindingSpec.scala
> SAR-8179 update eligibility submission and PageIdBindings

- app/featureswitch/core/config/FeatureSwitchingModule.scala
- app/utils/Navigator.scala
> SAR-8281: NIP feature switch

- app/controllers/ThresholdInTwelveMonthsController.scala
- app/models/BusinessEntity.scala
- app/utils/Navigator.scala
- app/utils/PageIdBinding.scala
> SAR-8372 Updated NETP checks to include non uk

- app/controllers/TurnoverEstimateController.scala
- test/controllers/TurnoverEstimateControllerSpec.scala
> SAR-8420: Skip zero-rated question if the turnover is £0

- app/controllers/RegisteringBusinessController.scala
- app/forms/RegisteringBusinessFormProvider.scala
- app/models/RegisteringBusiness.scala
- app/services/VatRegistrationService.scala
- app/utils/Navigator.scala
- app/utils/PageIdBinding.scala
- app/utils/UserAnswers.scala
- app/views/registeringBusiness.scala.html
- conf/messages
- it/controllers/EligibleControllerISpec.scala
- it/controllers/RegisteringBusinessControllerISpec.scala
- test/controllers/RegisteringBusinessControllerSpec.scala
- test/forms/RegisteringBusinessFormProviderSpec.scala
- test/services/VatRegistrationServiceSpec.scala
- test/utils/PageIdBindingSpec.scala
- test/views/RegisteringBusinessViewSpec.scala
**Feature alignment**
Adjusted the wording of the content on the registering business page and changed the routing to incorporate the Third Party Transactor feature switch
> SAR-8468 Updated content and routing for registering business page

- app/controllers/ThresholdInTwelveMonthsController.scala
- app/featureswitch/core/config/FeatureSwitchingModule.scala
- app/utils/Navigator.scala
- app/utils/PageIdBinding.scala
- it/controllers/ThresholdInTwelveMonthsControllerISpec.scala
- test/controllers/ThresholdInTwelveMonthsControllerSpec.scala
> SAR-8596: Added feature switch for Individual flow and routing

- app/controllers/NinoController.scala
- app/controllers/TaxableSuppliesInUkController.scala
- app/controllers/TrafficManagementResolverController.scala
- app/identifiers/TrafficManagementResolverId.scala
- app/utils/Navigator.scala
- conf/app.routes
- it/controllers/NinoControllerISpec.scala
- it/controllers/RegistrationReasonControllerISpec.scala
- it/controllers/TaxableSuppliesInUkControllerISpec.scala
- it/controllers/TrafficManagementResolverControllerISpec.scala
- test/controllers/NinoControllerSpec.scala
> SAR-8597 Separated duplicated TM logic into its own controller

- app/forms/BusinessEntityOtherFormProvider.scala
- app/models/BusinessEntity.scala
- app/views/businessEntity.scala.html
- app/views/businessEntityOther.scala.html
- conf/messages
- it/controllers/InternationalActivitiesControllerISpec.scala
- test/controllers/BusinessEntityControllerSpec.scala
- test/forms/BusinessEntityOtherFormProviderSpec.scala
- test/views/BusinessEntityOtherViewSpec.scala
- test/views/BusinessEntityViewSpec.scala
> SAR-8852: Updated content for UK Company and removed VAT Group radio button

- app/featureswitch/core/config/FeatureSwitchingModule.scala
SAR-8941 [VRS-EL-FE] Add Feature Switch for VAT Group registration
> SAR-8941 add feature switch for enabling VAT Group registration

- app/controllers/InvolvedInOtherBusinessController.scala
- app/views/involvedInOtherBusiness.scala.html
- test/controllers/InvolvedInOtherBusinessControllerSpec.scala
- test/views/InvolvedInOtherBusinessViewSpec.scala
> SAR-8943: Hide VatGroup bullet on InvolvedInOtherBusiness page

- app/controllers/RegistrationReasonController.scala
- app/utils/Navigator.scala
- app/utils/PageIdBinding.scala
- app/views/RegistrationReasonView.scala.html
- it/controllers/RegistrationReasonControllerISpec.scala
- test/views/RegistrationReasonViewSpec.scala
SAR-8942 “[VRS-EL-FE] Update reg reason page to show groups option and update routing”
- Reg reason page updated to show vat group option.
- Skipped threshold pages in the journey.
> SAR-8942 update reg reason page to show vat group option

- app/controllers/RegistrationReasonController.scala
- app/utils/UserAnswers.scala
- app/views/RegistrationReasonView.scala.html
- test/views/RegistrationReasonViewSpec.scala
SAR-8942 display VAT group option when rendering bad request page
**Bug fix**
- Check if UKCompany before displaying VAT Group option in reg reason page
- Display VAT group option when rendering bad request page
> SAR-8942 check if UKCompany before displaying VAT Group option

- app/featureswitch/core/config/FeatureSwitchingModule.scala
- app/utils/Navigator.scala
- app/utils/PageIdBinding.scala
- it/controllers/InvolvedInOtherBusinessControllerISpec.scala
> SAR-9026 Added FS to skip racehorces page

- app/featureswitch/core/config/FeatureSwitchingModule.scala
> SAR-9083: TOGC FS added

- app/featureswitch/core/config/FeatureSwitchingModule.scala
- app/utils/Navigator.scala
- it/controllers/VATExemptionISpec.scala
- it/controllers/VATRegistrationExceptionISpec.scala
SAR-9078 [VRS-EL-FE] Add feature switch and when its enabled update exception and exemption pages to allow continuing after choosing "yes"
> SAR-9078 update exception and exemption pages to allow continuing after choosing yes

- app/controllers/RegistrationReasonController.scala
- app/utils/Navigator.scala
- app/utils/UserAnswers.scala
- app/views/RegistrationReasonView.scala.html
- it/controllers/RegisteringBusinessControllerISpec.scala
- it/controllers/RegistrationReasonControllerISpec.scala
- it/controllers/TrafficManagementResolverControllerISpec.scala
- test/views/RegistrationReasonViewSpec.scala
> SAR-9084/SAR-9085 Updated the registration reason page and routing around it

- app/utils/Navigator.scala
- it/controllers/VATExemptionISpec.scala
- test/utils/NavigatorSpec.scala
> SAR-9077/SAR-9080-fix Updated the zero rated/exemption page routing for overseas and vat groups

- app/controllers/PreviousBusinessNameController.scala
- app/forms/PreviousBusinessNameFormProvider.scala
- app/identifiers/PreviousBusinessNameId.scala
- app/utils/Navigator.scala
- app/utils/PageIdBinding.scala
- app/utils/UserAnswers.scala
- app/views/PreviousBusinessName.scala.html
- conf/app.routes
- conf/messages
- it/controllers/DateOfBusinessTransferControllerISpec.scala
- it/controllers/EligibleControllerISpec.scala
- it/controllers/PreviousBusinessNameISpec.scala
- test/forms/PreviousBusinessNameFormProviderSpec.scala
- test/services/VatRegistrationServiceSpec.scala
- test/utils/PageIdBindingSpec.scala
- test/views/PreviousBusinessNameViewSpec.scala
> SAR-9087: Added TOGC Previous Business Name page and tests

- app/utils/PageIdBinding.scala
- test/services/VatRegistrationServiceSpec.scala
- test/utils/PageIdBindingSpec.scala
> SAR-9087: Updated PageIdBinding to fix build pipeline

- app/controllers/KeepOldVrnController.scala
- app/forms/KeepOldVrnFormProvider.scala
- app/identifiers/KeepOldVrnId.scala
- app/utils/Navigator.scala
- app/utils/UserAnswers.scala
- app/views/KeepOldVrn.scala.html
- conf/app.routes
- conf/messages
- it/controllers/KeepOldVrnControllerISpec.scala
- test/forms/KeepOldVrnFormProviderSpec.scala
- test/views/KeepOldVrnViewSpec.scala
> SAR-9089: Added TOGC Keep Old VRN page and tests

- app/controllers/VATNumberController.scala
- app/forms/VATNumberFormProvider.scala
- app/forms/mappings/Constraints.scala
- app/identifiers/VATNumberId.scala
- app/utils/Navigator.scala
- app/utils/UserAnswers.scala
- app/views/VATNumber.scala.html
- conf/app.routes
- conf/messages
- it/controllers/EligibleControllerISpec.scala
- it/controllers/PreviousBusinessNameISpec.scala
- it/controllers/VATNumberControllerISpec.scala
- project/AppDependencies.scala
- test/forms/PreviousBusinessNameFormProviderSpec.scala
- test/forms/VATNumberFormProviderSpec.scala
- test/forms/mappings/ConstraintsSpec.scala
- test/views/VATNumberViewSpec.scala
> SAR-9088: Previous vat number page for TOGC added

- app/controllers/TermsAndConditionsController.scala
- app/identifiers/TermsAndConditionsId.scala
- app/utils/Navigator.scala
- app/views/TermsAndConditions.scala.html
- conf/app.routes
- conf/messages
- it/controllers/TermsAndConditionsControllerISpec.scala
- test/views/TermsAndConditionsViewSpec.scala
> SAR-9194: Added Terms and Conditions page, tests and updated routing

- app/controllers/VATExemptionController.scala
- app/controllers/VATRegistrationExceptionController.scala
- it/controllers/VATRegistrationExceptionISpec.scala
- it/controllers/VatExemptionControllerISpec.scala
> SAR-9227: Logic change for TM upsert on exemptiion/exception flow

- app/featureswitch/core/config/FeatureSwitchingModule.scala
- app/views/involvedInOtherBusiness.scala.html
- conf/messages
- test/views/InvolvedInOtherBusinessViewSpec.scala
> SAR-9378: OBI FS and content added

- app/controllers/InvolvedInOtherBusinessController.scala
- app/forms/InvolvedInOtherBusinessFormProvider.scala
- app/services/VatRegistrationService.scala
- app/utils/Navigator.scala
- app/utils/PageIdBinding.scala
- app/views/involvedInOtherBusiness.scala.html
- conf/messages
- it/controllers/InternationalActivitiesControllerISpec.scala
- test/forms/InvolvedInOtherBusinessFormProviderSpec.scala
- test/views/InvolvedInOtherBusinessViewSpec.scala
> SAR-9499 Updated feature switch logic and dynamic messages for InvolvedInOtherBusiness

- app/controllers/FixedEstablishmentController.scala
- app/controllers/RegistrationReasonController.scala
- app/services/DataCleardownService.scala
- it/controllers/FixedEstablishmentControllerISpec.scala
> SAR-9733 Added data cleardown service, added cleardown on fixed establishment answer change

- a11y/pages/KeepOldVrnA11ySpec.scala
- app/repositories/SessionRepository.scala
- conf/application.conf
- it/helpers/FakeConfig.scala
- it/helpers/IntegrationSpecBase.scala
- it/helpers/SessionStub.scala
- it/repositories/SessionRepositoryISpec.scala
- project/AppDependencies.scala
> SAR-9675 | [VRS-EL] Migrate to hmrc-mongo

- app/controllers/VATRegistrationExceptionController.scala
- app/featureswitch/core/config/FeatureSwitchingModule.scala
- app/utils/Navigator.scala
- it/controllers/VATRegistrationExceptionISpec.scala
Remove exception exemption flow
> SAR-9859 | Remove Exception Exemption flow

- app/connectors/VatRegistrationConnector.scala
> SAR-10088 API connections cleaned up

- app/views/InternationalActivityDropout.scala.html
- test/views/InternationalActivitiesDropoutViewSpec.scala
> SAR-10215: Updated URL for International Business Activities Dropout view and added viewspec

- app/services/VatRegistrationService.scala
- app/views/CurrentlyTrading.scala.html
- conf/messages
- test/views/CurrentlyTradingViewSpec.scala
> SAR-10249 changed the No answer content for currently trading question

- app/featureswitch/core/config/FeatureSwitchingModule.scala
- app/utils/Navigator.scala
- it/controllers/InternationalActivitiesControllerISpec.scala
[SAR-10461](https://jira.tools.tax.service.gov.uk/browse/SAR-10461)
Remove toggle for non-incorp-trust-flow FS
> SAR-10461 | Remove non-incorp-trust flow FS check

- app/featureswitch/core/config/FeatureSwitchingModule.scala
- app/utils/Navigator.scala
- it/controllers/InternationalActivitiesControllerISpec.scala
SAR-10453 remove charity flow feature switch
> SAR-10453 remove charity flow feature switch

- app/featureswitch/core/config/FeatureSwitchingModule.scala
- app/utils/Navigator.scala
- it/controllers/InternationalActivitiesControllerISpec.scala
[SAR-10469](https://jira.tools.tax.service.gov.uk/browse/SAR-10469)
Remove enable-unincorporated-association journey FS
> SAR-10469 | Remove unincorporated association journey FS

- app/featureswitch/core/config/FeatureSwitchingModule.scala
- app/utils/Navigator.scala
- it/controllers/InternationalActivitiesControllerISpec.scala
[SAR-10484](https://jira.tools.tax.service.gov.uk/browse/SAR-10484)
Remove RegisteredSociety FS
> SAR-10484 | Remove registered society FS

- app/featureswitch/core/config/FeatureSwitchingModule.scala
- app/utils/Navigator.scala
- it/controllers/BusinessEntityOverseasControllerISpec.scala
- it/controllers/FixedEstablishmentControllerISpec.scala
SAR-10477 remove NETP flow feature switch
> SAR-10477 remove NETP flow feature switch

- app/models/BusinessEntity.scala
- app/models/RegisteringBusiness.scala
- app/models/RegistrationReason.scala
- app/services/VatRegistrationService.scala
- test/services/VatRegistrationServiceSpec.scala
[SAR-10562](https://jira.tools.tax.service.gov.uk/browse/SAR-10562)
**Bug fix**
Handle message translation on CYA based on language settings on VRS-FE. To allow that, pass message keys as part of eligibilityData to VRS-FE
> SAR-10562 | Pass message keys as part of eligibilityData for translation on VRS-FE

- app/controllers/BaseController.scala
- it/controllers/AgriculturalFlatRateControllerISpec.scala
- it/controllers/BusinessEntityControllerISpec.scala
- it/controllers/BusinessEntityOtherControllerISpec.scala
- it/controllers/BusinessEntityOverseasControllerISpec.scala
- it/controllers/BusinessEntityPartnershipControllerISpec.scala
- it/controllers/ChooseNotToRegisterControllerISpec.scala
- it/controllers/DoNotNeedToRegisterControllerISpec.scala
- it/controllers/FixedEstablishmentControllerISpec.scala
- it/controllers/InternationalActivitiesControllerISpec.scala
- it/controllers/InvolvedInOtherBusinessControllerISpec.scala
- it/controllers/KeepOldVrnControllerISpec.scala
- it/controllers/MtdInformationControllerISpec.scala
- it/controllers/NinoControllerControllerISpec.scala
- it/controllers/RacehorsesControllerISpec.scala
- it/controllers/RegisteringBusinessControllerISpec.scala
- it/controllers/RegistrationReasonControllerISpec.scala
- it/controllers/TaxableSuppliesInUkControllerISpec.scala
- it/controllers/ThresholdNextThirtyDaysControllerISpec.scala
- it/controllers/ThresholdPreviousThirtyDaysControllerISpec.scala
- it/controllers/ThresholdTaxableSuppliesControllerISpec.scala
- it/controllers/VATRegistrationExceptionISpec.scala
- it/controllers/VatExceptionKickoutControllerISpec.scala
- it/controllers/VoluntaryRegistrationControllerISpec.scala
> Update form bindings

- app/controllers/TermsAndConditionsController.scala
- app/views/InternationalActivities.scala.html
- app/views/KeepOldVrn.scala.html
- app/views/RegisteringBusinessView.scala.html
- app/views/RegistrationReasonView.scala.html
- app/views/TermsAndConditions.scala.html
- app/views/VATNumber.scala.html
- conf/messages
- conf/messages.cy
- test/utils/JsoupElementExtractor.scala
- test/views/BusinessEntityOverseasViewSpec.scala
- test/views/BusinessEntityPartnershipViewSpec.scala
- test/views/InternationalActivitiesViewSpec.scala
- test/views/RegisteringBusinessViewSpec.scala
- test/views/RegistrationReasonViewSpec.scala
- test/views/TermsAndConditionsViewSpec.scala
- test/views/ThresholdInTwelveMonthsViewSpec.scala
- test/views/VATNumberViewSpec.scala
> SAR-10905: Updated content to align with prototype

- conf/messages.cy
> SAR-10985: Added remaining Welsh content

- app/controllers/BusinessEntityController.scala
- app/featureswitch/core/config/FeatureSwitchingModule.scala
- app/utils/Navigator.scala
- conf/messages
- conf/messages.cy
- it/controllers/BusinessEntityControllerISpec.scala
- it/controllers/InternationalActivitiesControllerISpec.scala
> SAR-11060: Removed ST feature switch

- app/featureswitch/core/config/FeatureSwitchingModule.scala
- app/utils/Navigator.scala
- it/controllers/InternationalActivitiesControllerISpec.scala
> SAR-11062: Removed Partnership feature switch

- app/featureswitch/core/config/FeatureSwitchingModule.scala
- app/utils/Navigator.scala
- conf/messages.cy
- it/controllers/RegisteringBusinessControllerISpec.scala
> SAR-11063: Removed Third Party Transactor feature switch

- app/forms/DateOfBusinessTransferFormProvider.scala
- app/forms/ThresholdInTwelveMonthsFormProvider.scala
- app/forms/ThresholdNextThirtyDaysFormProvider.scala
- app/forms/ThresholdPreviousThirtyDaysFormProvider.scala
- app/forms/ThresholdTaxableSuppliesFormProvider.scala
- app/forms/mappings/LocalDateFormatter.scala
- app/services/VatRegistrationService.scala
- app/utils/MessageDateFormat.scala
- app/views/ThresholdTaxableSupplies.scala.html
- app/views/components/inputDate.scala.html
- conf/messages
- conf/messages.cy
- test/forms/DateOfBusinessTransferFormProviderSpec.scala
- test/forms/ThresholdTaxableSuppliesFormProviderSpec.scala
- test/forms/mappings/LocalDateFormatterSpec.scala
- test/services/VatRegistrationServiceSpec.scala
- test/views/DateOfBusinessTransferViewSpec.scala
- test/views/TaxableSuppliesInUkViewSpec.scala
- test/views/ThresholdTaxableSuppliesViewSpec.scala
> SAR-11090 Updated Taxable Supplies in UK content and updated the date validation for non established flow

- conf/application.conf
> Removed unused configs in application.conf

- app/controllers/BaseController.scala
- app/controllers/ChoseNotToRegisterController.scala
- app/controllers/DoNotNeedToRegisterController.scala
- app/controllers/EligibilityDropoutController.scala
- app/controllers/FeedbackController.scala
- app/controllers/IndexController.scala
- app/controllers/RegReasonResolverController.scala
- app/controllers/SessionExpiredController.scala
- app/controllers/UnauthorisedController.scala
- app/models/RegisteringBusiness.scala
- it/controllers/IndexControllerISpec.scala
- it/helpers/AuthHelpers.scala
- it/helpers/WiremockHelper.scala
> SAR-11197 Added handling for missing sessions on journey init/changeLink routes

- README.md
[SAR-11185](https://jira.tools.tax.service.gov.uk/browse/SAR-11185)
Update README regarding feature-switches
> SAR-11185 | Update README

- app/views/fixed_establishment_variant_c.scala.html
- conf/messages
- conf/messages.cy
- test/views/FixedEstablishmentVariantCViewSpec.scala
> DL-10553 - Fixed Establishment Optimizely experiment variant C

- app/views/layouts/layout.scala.html
- conf/application.conf
> DL-10557 - added Optimizely snippet

- app/views/fixed_establishment_variant_a.scala.html
- conf/messages
- conf/messages.cy
- test/views/FixedEstablishmentVariantAViewSpec.scala
> DL-10551 - Fixed Establishment Optimizely experiment variant A

- app/forms/FixedEstablishmentFormProviderVariantB.scala
- app/views/FixedEstablishmentVariantB.scala.html
- conf/messages
- conf/messages.cy
- test/views/FixedEstablishmentViewVarBSpec.scala
DL-10552 Fixed establishment page variant B
New feature
Adds variant `FixedEstablishlishmentVariantB` view, as well as new form provider `FixedEstablishmentFormProviderVariantB` to provide updated error message.
> DL-10552 fixed establishment variant B

- app/utils/Navigator.scala
> DL-10644 - fixed the fixed establishment page bug

- app/featureswitch/api/services/FeatureSwitchService.scala
- app/featureswitch/core/models/FeatureSwitchSetting.scala
> Refactor feature switches

- app/views/KeepOldVrn.scala.html
- conf/messages
- conf/messages.cy
- project/plugins.sbt
- test/views/KeepOldVrnViewSpec.scala
Reverts hmrc/vat-registration-eligibility-frontend#347
> Revert "DL-11886 - changed content on keep vat registration number"

- app/controllers/ThresholdNextThirtyDaysController.scala
- app/controllers/ThresholdPreviousThirtyDaysController.scala
- app/forms/ThresholdNextThirtyDaysFormProvider.scala
- app/forms/ThresholdPreviousThirtyDaysFormProvider.scala
- test/forms/ThresholdNextThirtyDaysFormProviderSpec.scala
- test/forms/ThresholdPreviousThirtyDaysFormProviderSpec.scala
- test/views/ThresholdNextThirtyDaysViewSpec.scala
- test/views/ThresholdPreviousThirtyDaysViewSpec.scala
> DL-13331 VAT threshold error messages

- app/repositories/SessionRepository.scala
use local date time
**Bug fix**
> DDCYLS-4987

- app/repositories/SessionRepository.scala
- test/repositories/DatedCacheMapSpec.scala
> add zone to lastUpdated field

- conf/application.conf
- test/views/MtdInformationViewSpec.scala
> DL-14505 Fixed MTD for VAT guidance link

- conf/logback.xml
> DL-14427: Updated invalid Pekko and Mongo configuration in logback.xml

- README.md
- app/featureswitch/core/config/FeatureSwitchingModule.scala
- app/featureswitch/core/models/FeatureSwitch.scala
- conf/application.conf
- test/repositories/DatedCacheMapSpec.scala
**New feature** (delete as appropriate)
add a feature switch for DL-15898
> add feature switch for DL-15898

- conf/application.conf
> [DL-16928] Hide optimizely.projectId from all env configs
